package com.example.iot.Entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;

import java.time.Instant;
@Entity
public class PeopleCount {
    @Id
    @GeneratedValue
    private Long id;  // Auto-generated by the database

    @Column(nullable = false)
    private int count;

    @CreatedDate
    private Instant timestamp;  // Use Instant to store the timestamp of data insertion

    // Getters and setters
    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    @PrePersist
    public void setTimestamp() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now();
        }
    }

    @Override
    public String toString() {
        return "PeopleCount{" +
                "count=" + count +
                ", timestamp=" + timestamp +
                '}';
    }
}
